import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import TrainingPlan from "../components/TrainingPlan";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const session = useSession()
  return (
    <>
      <>
      <Head>
        <title>Welcome to makeUtrain</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-2 m-1 border border-black w-6/6 h-screen flex flex-col bg-gray-100">
        <TrainingPlan />
      </div>
      </>
      : 
      <>
        <div className="text-center">
          <h1 className="text-3xl p-2" >Welcome to makeUtrain</h1>
          <h1>Please login</h1>
          <AuthShowcase />
        </div>
      </>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div>
      <p >
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
